---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mixmode.fullname" . }}
  labels:
    {{- include "mixmode.labels" . | nindent 4 }}
spec:
  ports:
    - port: 22
      protocol: TCP
      targetPort: 22
      name: ssh
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http-web
    - port: 443
      protocol: TCP
      targetPort: 443
      name: https-web
  selector:
    kubevirt.io/vm: {{ include "mixmode.fullname" . }}
  type: ClusterIP