apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mixmode-sensor
  namespace: mixmode
spec:
  targetNamespace: mixmode
  releaseName: mixmode-sensor
  interval: 5m
  timeout: 10m
  chart:
    spec:
      interval: 1m
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: mixmode-sensor
  values:
    image:
      tag: "###ZARF_CONST_TAG###"
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  dependsOn:
    - name: istio
      namespace: bigbang
    - name: kubevirt
      namespace: kubevirt
